#!/bin/bash
if [ "" == "$1" ] ; then
	echo "Bitte Versionsnummer angeben."
	exit
fi
scp advancedcaching_$1_all.ipk root@192.168.0.202:
ssh root@192.168.0.202 "opkg-cl install advancedcaching_$1_all.ipk"
