# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/qt/GeocacheDetailsWindow.ui'
#
# Created: Wed Aug  4 11:14:59 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GeocacheDetailsWindow(object):
    def setupUi(self, GeocacheDetailsWindow):
        GeocacheDetailsWindow.setObjectName("GeocacheDetailsWindow")
        GeocacheDetailsWindow.resize(800, 480)
        self.centralwidget = QtGui.QWidget(GeocacheDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInformation = QtGui.QWidget()
        self.tabInformation.setObjectName("tabInformation")
        self.gridLayout = QtGui.QGridLayout(self.tabInformation)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelFullName = QtGui.QLabel(self.tabInformation)
        self.labelFullName.setText("")
        self.labelFullName.setObjectName("labelFullName")
        self.gridLayout.addWidget(self.labelFullName, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.labelID = QtGui.QLabel(self.tabInformation)
        self.labelID.setText("")
        self.labelID.setObjectName("labelID")
        self.gridLayout.addWidget(self.labelID, 1, 1, 1, 1)
        self.labelType = QtGui.QLabel(self.tabInformation)
        self.labelType.setText("")
        self.labelType.setObjectName("labelType")
        self.gridLayout.addWidget(self.labelType, 2, 1, 1, 1)
        self.labelSize = QtGui.QLabel(self.tabInformation)
        self.labelSize.setText("")
        self.labelSize.setObjectName("labelSize")
        self.gridLayout.addWidget(self.labelSize, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tabInformation)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.labelTerrain = QtGui.QLabel(self.tabInformation)
        self.labelTerrain.setText("")
        self.labelTerrain.setObjectName("labelTerrain")
        self.gridLayout.addWidget(self.labelTerrain, 4, 1, 1, 1)
        self.labelDifficulty = QtGui.QLabel(self.tabInformation)
        self.labelDifficulty.setText("")
        self.labelDifficulty.setObjectName("labelDifficulty")
        self.gridLayout.addWidget(self.labelDifficulty, 5, 1, 1, 1)
        self.labelOwner = QtGui.QLabel(self.tabInformation)
        self.labelOwner.setText("")
        self.labelOwner.setObjectName("labelOwner")
        self.gridLayout.addWidget(self.labelOwner, 6, 1, 1, 1)
        self.labelStatus = QtGui.QLabel(self.tabInformation)
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tabInformation, "")
        self.tabDescription = QtGui.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabDescription)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea_2 = QtGui.QScrollArea(self.tabDescription)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 770, 387))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelDescription = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDescription.setTextFormat(QtCore.Qt.RichText)
        self.labelDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.horizontalLayout_6.addWidget(self.labelDescription)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabLogsHints = QtGui.QWidget()
        self.tabLogsHints.setObjectName("tabLogsHints")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabLogsHints)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.tabLogsHints)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 770, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelLogs = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelLogs.setTextFormat(QtCore.Qt.RichText)
        self.labelLogs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelLogs.setWordWrap(True)
        self.labelLogs.setObjectName("labelLogs")
        self.horizontalLayout_2.addWidget(self.labelLogs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.pushButtonShowHint = QtGui.QPushButton(self.tabLogsHints)
        self.pushButtonShowHint.setObjectName("pushButtonShowHint")
        self.verticalLayout.addWidget(self.pushButtonShowHint)
        self.tabWidget.addTab(self.tabLogsHints, "")
        self.tabCoordinateCalculation = QtGui.QWidget()
        self.tabCoordinateCalculation.setObjectName("tabCoordinateCalculation")
        self.tabWidget.addTab(self.tabCoordinateCalculation, "")
        self.tabCoordinates = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCoordinates.sizePolicy().hasHeightForWidth())
        self.tabCoordinates.setSizePolicy(sizePolicy)
        self.tabCoordinates.setObjectName("tabCoordinates")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabCoordinates)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtGui.QTableWidget(self.tabCoordinates)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tabCoordinates, "")
        self.tabImages = QtGui.QWidget()
        self.tabImages.setObjectName("tabImages")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabImages)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidgetImages = QtGui.QListWidget(self.tabImages)
        self.listWidgetImages.setViewMode(QtGui.QListView.IconMode)
        self.listWidgetImages.setObjectName("listWidgetImages")
        self.horizontalLayout_4.addWidget(self.listWidgetImages)
        self.tabWidget.addTab(self.tabImages, "")
        self.tabNotes = QtGui.QWidget()
        self.tabNotes.setObjectName("tabNotes")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabNotes)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabNotes)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_5.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tabNotes, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        GeocacheDetailsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GeocacheDetailsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuGeocache = QtGui.QMenu(self.menubar)
        self.menuGeocache.setObjectName("menuGeocache")
        GeocacheDetailsWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GeocacheDetailsWindow)
        self.statusbar.setObjectName("statusbar")
        GeocacheDetailsWindow.setStatusBar(self.statusbar)
        self.actionSet_as_Target = QtGui.QAction(GeocacheDetailsWindow)
        self.actionSet_as_Target.setObjectName("actionSet_as_Target")
        self.actionWrite_Fieldnote = QtGui.QAction(GeocacheDetailsWindow)
        self.actionWrite_Fieldnote.setObjectName("actionWrite_Fieldnote")
        self.actionDownload_Details = QtGui.QAction(GeocacheDetailsWindow)
        self.actionDownload_Details.setObjectName("actionDownload_Details")
        self.menuGeocache.addAction(self.actionSet_as_Target)
        self.menuGeocache.addAction(self.actionWrite_Fieldnote)
        self.menuGeocache.addAction(self.actionDownload_Details)
        self.menubar.addAction(self.menuGeocache.menuAction())

        self.retranslateUi(GeocacheDetailsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeocacheDetailsWindow)

    def retranslateUi(self, GeocacheDetailsWindow):
        GeocacheDetailsWindow.setWindowTitle(QtGui.QApplication.translate("GeocacheDetailsWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Full Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Difficulty", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Owner", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInformation), QtGui.QApplication.translate("GeocacheDetailsWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDescription.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), QtGui.QApplication.translate("GeocacheDetailsWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLogs.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonShowHint.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Show Hint", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogsHints), QtGui.QApplication.translate("GeocacheDetailsWindow", "Logs && Hints", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoordinateCalculation), QtGui.QApplication.translate("GeocacheDetailsWindow", "Coordinate Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoordinates), QtGui.QApplication.translate("GeocacheDetailsWindow", "Coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImages), QtGui.QApplication.translate("GeocacheDetailsWindow", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), QtGui.QApplication.translate("GeocacheDetailsWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGeocache.setTitle(QtGui.QApplication.translate("GeocacheDetailsWindow", "Geocache", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_as_Target.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Set as Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWrite_Fieldnote.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Write Fieldnote", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_Details.setText(QtGui.QApplication.translate("GeocacheDetailsWindow", "Download Details", None, QtGui.QApplication.UnicodeUTF8))

