# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/qt/OptionsDialog.ui'
#
# Created: Wed Aug  4 14:54:51 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(412, 384)
        self.verticalLayout = QtGui.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(OptionsDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditUserName = QtGui.QLineEdit(self.groupBox)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout.addWidget(self.lineEditUserName, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditPassword = QtGui.QLineEdit(self.groupBox)
        self.lineEditPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(OptionsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxShowName = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxShowName.setObjectName("checkBoxShowName")
        self.gridLayout_2.addWidget(self.checkBoxShowName, 1, 0, 1, 1)
        self.checkBoxDoubleSize = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxDoubleSize.setObjectName("checkBoxDoubleSize")
        self.gridLayout_2.addWidget(self.checkBoxDoubleSize, 2, 0, 1, 1)
        self.checkBoxHideFound = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxHideFound.setObjectName("checkBoxHideFound")
        self.gridLayout_2.addWidget(self.checkBoxHideFound, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(OptionsDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBoxTTS = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxTTS.setObjectName("comboBoxTTS")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.comboBoxTTS.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxTTS, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonBox = QtGui.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), OptionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        OptionsDialog.setWindowTitle(QtGui.QApplication.translate("OptionsDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("OptionsDialog", "Login Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OptionsDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OptionsDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OptionsDialog", "Please make sure that the website language ist set to english. Otherwise, downloading of geocaches won\'t work.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("OptionsDialog", "Map Display", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowName.setText(QtGui.QApplication.translate("OptionsDialog", "Show Geocache Names on Map", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDoubleSize.setText(QtGui.QApplication.translate("OptionsDialog", "Show Map in double size (ugly!)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxHideFound.setText(QtGui.QApplication.translate("OptionsDialog", "Hide Found Geocaches", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("OptionsDialog", "Text-to-speech settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OptionsDialog", "Enable Voice Guidance", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(0, QtGui.QApplication.translate("OptionsDialog", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(1, QtGui.QApplication.translate("OptionsDialog", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(2, QtGui.QApplication.translate("OptionsDialog", "10 Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(3, QtGui.QApplication.translate("OptionsDialog", "20 Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(4, QtGui.QApplication.translate("OptionsDialog", "30 Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(5, QtGui.QApplication.translate("OptionsDialog", "50 Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(6, QtGui.QApplication.translate("OptionsDialog", "100 Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(7, QtGui.QApplication.translate("OptionsDialog", "3 Minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(8, QtGui.QApplication.translate("OptionsDialog", "5 Minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTTS.setItemText(9, QtGui.QApplication.translate("OptionsDialog", "10 Minutes", None, QtGui.QApplication.UnicodeUTF8))

